Document: glancepush
Title: Debian glancepush Manual
Author: <insert document author here>
Abstract: This manual describes what glancepush is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glancepush/glancepush.sgml.gz

Format: postscript
Files: /usr/share/doc/glancepush/glancepush.ps.gz

Format: text
Files: /usr/share/doc/glancepush/glancepush.text.gz

Format: HTML
Index: /usr/share/doc/glancepush/html/index.html
Files: /usr/share/doc/glancepush/html/*.html
