.TH gppublish 1 "2013/02/22" "glancepush-0.1" 
.SH NAME
gppublish \- publishes an image into glance

.SH SYNOPSOS
gppublish [-q] {imagename|imagefile}

.SH DESCRIPTION
If -q is provided, the file pointed by \fBimagefile\fR will be uploaded to a quarantined zone. The tenant \fBtest_tenant\fR configured in the configuration file will be granted access to the image.

If -q is absent, the image already uploaded named \fBimagename.q\fR will be released (renamed \fBimagename\fR and publicly released).
.RE

.SH "AUTHOR(S)"
.na
.nf
Mattieu Puel @ IN2P3-CC

.SH SEE ALSO
.B gppublish (1), gppolcheck (1), gpextractmeta (1), glancepushrc (5)

